export interface Company { id: string; code: string; legal_name: string; trade_name?: string | null; tax_id?: string | null; country: string; currency: string; tax_rate: number; invoice_prefix: string; zoho_org_id?: string | null; active: boolean }
export interface Branch { id: string; company_id: string; code: string; name: string; address?: string | null; phone?: string | null; monthly_goal: number; active: boolean }
export interface Staff { id: string; user_id?: string | null; company_id: string; branch_id?: string | null; name: string; email?: string | null; role: 'admin' | 'gerente' | 'vendedor' | 'optometrista' | 'cajero' | 'almacen'; commission_pct: number; max_discount_pct: number; monthly_goal: number; active: boolean }
export interface Customer { id: string; company_id: string; branch_id?: string | null; code: string; first_name: string; last_name: string; email?: string | null; phone?: string | null; tax_id?: string | null; birth_date?: string | null; gender?: string | null; address?: string | null; source: string; referred_by?: string | null; balance: number; tags: string[]; notes?: string | null; created_at: string; zoho_contact_id?: string | null }
export interface Product { id: string; sku: string; barcode?: string | null; name: string; category: 'armazon' | 'lente' | 'lente_contacto' | 'solar' | 'accesorio' | 'servicio'; brand?: string | null; model?: string | null; color?: string | null; cost: number; price: number; min_stock: number; track_stock: boolean; active: boolean }
export interface Eye { sph?: number; cyl?: number; axis?: number; add?: number; va?: string }
export interface Rx { od?: Eye; oi?: Eye; pd?: number; notes?: string }
export interface Exam { id: string; company_id: string; branch_id: string; customer_id: string; optometrist_id?: string | null; template: 'adulto' | 'nino'; exam_date: string; reason?: string | null; autorefraction: Rx; rx_initial: Rx; rx_final: Rx; rx_final_transposed: Rx; diagnosis?: string | null; recommendation?: string | null; next_review_date?: string | null; status: string; created_at: string; customer?: Customer; optometrist?: Staff; branch?: Branch }
export interface Sale { id: string; company_id: string; branch_id: string; customer_id?: string | null; seller_id?: string | null; number: string; sale_date: string; source?: string | null; subtotal: number; discount: number; tax: number; total: number; paid: number; cost_total: number; status: string; delivery_status: string; delivered_at?: string | null; commission_amount: number; zoho_invoice_id?: string | null; zoho_sync_status: string; customer?: Customer; seller?: Staff; branch?: Branch; sale_items?: SaleItem[]; payments?: Payment[] }
export interface SaleItem { id: string; product_id?: string | null; description: string; category?: string | null; qty: number; unit_price: number; discount_pct: number; line_total: number }
export interface Payment { id: string; method: string; amount: number; reference?: string | null; created_at: string }
export interface Quote { id: string; company_id: string; branch_id: string; customer_id: string; exam_id?: string | null; seller_id?: string | null; number: string; status: string; subtotal: number; discount: number; tax: number; total: number; valid_until?: string | null; next_followup_at?: string | null; last_contact_at?: string | null; lost_reason?: string | null; notes?: string | null; created_at: string; customer?: Customer; seller?: Staff; quote_items?: { id: string; product_id?: string | null; description: string; qty: number; unit_price: number; discount_pct: number; line_total: number }[] }
export interface CashSession { id: string; company_id: string; branch_id: string; opened_by?: string | null; opened_at: string; closed_at?: string | null; opening_amount: number; expected_cash?: number | null; counted_cash?: number | null; difference?: number | null; status: 'abierta' | 'cerrada'; notes?: string | null; opener?: Staff; cash_movements?: { id: string; type: string; amount: number; concept: string; created_at: string }[]; payments?: Payment[] }
export interface LabOrder { id: string; number: string; company_id: string; branch_id: string; sale_id?: string | null; customer_id: string; lab_name: string; status: string; lens_type?: string | null; treatment?: string | null; frame?: string | null; promised_at?: string | null; sent_at?: string | null; received_at?: string | null; delivered_at?: string | null; notified_at?: string | null; notes?: string | null; created_at: string; customer?: Customer; sale?: Sale; lab_order_events?: { id: string; status: string; note?: string | null; created_at: string }[] }
export interface Rma { id: string; number: string; company_id: string; branch_id: string; sale_id?: string | null; customer_id: string; product_id?: string | null; type: string; status: string; reason: string; resolution?: string | null; refund_amount: number; refund_method?: string | null; created_at: string; resolved_at?: string | null; customer?: Customer; product?: Product; sale?: Sale; rma_events?: { id: string; status: string; note?: string | null; created_at: string }[] }
export interface Transfer { id: string; number: string; from_branch_id: string; to_branch_id: string; status: string; intercompany: boolean; intercompany_doc_id?: string | null; note?: string | null; created_at: string; sent_at?: string | null; received_at?: string | null; from_branch?: Branch; to_branch?: Branch; transfer_items?: { id: string; product_id: string; qty: number; unit_cost: number; product?: Product }[] }
export interface IntercompanyDoc { id: string; number: string; issuer_company_id: string; receiver_company_id: string; doc_date: string; due_date?: string | null; concept: string; origin_type?: string | null; subtotal: number; tax: number; total: number; status: string; ar_status: string; ap_status: string; zoho_invoice_id?: string | null; zoho_bill_id?: string | null; zoho_sync_status: string; created_at: string; issuer_company?: Company; receiver_company?: Company; intercompany_items?: { id: string; description: string; qty: number; unit_price: number; line_total: number }[] }
export interface Alert { kind: string; company_id: string; branch_id?: string | null; ref_id: string; message: string; at: string; severity: 'alta' | 'media' | 'baja'; branch?: Branch }
export interface ZohoJob { id: string; company_id: string; event_type: string; target: string; entity_id?: string | null; idempotency_key: string; status: string; attempts: number; last_error?: string | null; next_retry_at?: string | null; zoho_id?: string | null; created_at: string; processed_at?: string | null; company?: Company }
export interface Appointment { id: string; customer_id: string; branch_id: string; optometrist_id?: string | null; scheduled_at: string; duration_min: number; status: string; source?: string | null; notes?: string | null; customer?: Customer; optometrist?: Staff }
